# Generated by Django 4.2.10 on 2024-02-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='point',
        ),
    ]
